// Code generated by MockGen. DO NOT EDIT.
// Source: balance_contract.go

// Package balance is a generated GoMock package.
package balance

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStorageAccess is a mock of StorageAccess interface
type MockStorageAccess struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAccessMockRecorder
}

// MockStorageAccessMockRecorder is the mock recorder for MockStorageAccess
type MockStorageAccessMockRecorder struct {
	mock *MockStorageAccess
}

// NewMockStorageAccess creates a new mock instance
func NewMockStorageAccess(ctrl *gomock.Controller) *MockStorageAccess {
	mock := &MockStorageAccess{ctrl: ctrl}
	mock.recorder = &MockStorageAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorageAccess) EXPECT() *MockStorageAccessMockRecorder {
	return m.recorder
}

// DepositMoney mocks base method
func (m *MockStorageAccess) DepositMoney(account_id, balance_id int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepositMoney", account_id, balance_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DepositMoney indicates an expected call of DepositMoney
func (mr *MockStorageAccessMockRecorder) DepositMoney(account_id, balance_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepositMoney", reflect.TypeOf((*MockStorageAccess)(nil).DepositMoney), account_id, balance_id, amount)
}

// WithdrawMoney mocks base method
func (m *MockStorageAccess) WithdrawMoney(account_id, balance_id int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawMoney", account_id, balance_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawMoney indicates an expected call of WithdrawMoney
func (mr *MockStorageAccessMockRecorder) WithdrawMoney(account_id, balance_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawMoney", reflect.TypeOf((*MockStorageAccess)(nil).WithdrawMoney), account_id, balance_id, amount)
}

// TransferMoney mocks base method
func (m *MockStorageAccess) TransferMoney(sender_account_id, sender_balance_id, receiver_account_id, receiver_balance_id int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferMoney", sender_account_id, sender_balance_id, receiver_account_id, receiver_balance_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferMoney indicates an expected call of TransferMoney
func (mr *MockStorageAccessMockRecorder) TransferMoney(sender_account_id, sender_balance_id, receiver_account_id, receiver_balance_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferMoney", reflect.TypeOf((*MockStorageAccess)(nil).TransferMoney), sender_account_id, sender_balance_id, receiver_account_id, receiver_balance_id, amount)
}

// GetBalance mocks base method
func (m *MockStorageAccess) GetBalance(account_id, balance_id int) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", account_id, balance_id)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance
func (mr *MockStorageAccessMockRecorder) GetBalance(account_id, balance_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockStorageAccess)(nil).GetBalance), account_id, balance_id)
}

// GetBalanceHistory mocks base method
func (m *MockStorageAccess) GetBalanceHistory(account_id, balance_id int, sort string, page int64) ([]Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceHistory", account_id, balance_id, sort, page)
	ret0, _ := ret[0].([]Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceHistory indicates an expected call of GetBalanceHistory
func (mr *MockStorageAccessMockRecorder) GetBalanceHistory(account_id, balance_id, sort, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceHistory", reflect.TypeOf((*MockStorageAccess)(nil).GetBalanceHistory), account_id, balance_id, sort, page)
}

// MockExchangeRateGetter is a mock of ExchangeRateGetter interface
type MockExchangeRateGetter struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeRateGetterMockRecorder
}

// MockExchangeRateGetterMockRecorder is the mock recorder for MockExchangeRateGetter
type MockExchangeRateGetterMockRecorder struct {
	mock *MockExchangeRateGetter
}

// NewMockExchangeRateGetter creates a new mock instance
func NewMockExchangeRateGetter(ctrl *gomock.Controller) *MockExchangeRateGetter {
	mock := &MockExchangeRateGetter{ctrl: ctrl}
	mock.recorder = &MockExchangeRateGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExchangeRateGetter) EXPECT() *MockExchangeRateGetterMockRecorder {
	return m.recorder
}

// GetExchangeRate mocks base method
func (m *MockExchangeRateGetter) GetExchangeRate(cur string) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRate", cur)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRate indicates an expected call of GetExchangeRate
func (mr *MockExchangeRateGetterMockRecorder) GetExchangeRate(cur interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRate", reflect.TypeOf((*MockExchangeRateGetter)(nil).GetExchangeRate), cur)
}
