// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go

// Package balance is a generated GoMock package.
package balance

import (
	storage "github.com/bernmarx/avito-assignment/internal/storage"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockstorageIfc is a mock of storageIfc interface
type MockstorageIfc struct {
	ctrl     *gomock.Controller
	recorder *MockstorageIfcMockRecorder
}

// MockstorageIfcMockRecorder is the mock recorder for MockstorageIfc
type MockstorageIfcMockRecorder struct {
	mock *MockstorageIfc
}

// NewMockstorageIfc creates a new mock instance
func NewMockstorageIfc(ctrl *gomock.Controller) *MockstorageIfc {
	mock := &MockstorageIfc{ctrl: ctrl}
	mock.recorder = &MockstorageIfcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockstorageIfc) EXPECT() *MockstorageIfcMockRecorder {
	return m.recorder
}

// Deposit mocks base method
func (m *MockstorageIfc) Deposit(id int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deposit indicates an expected call of Deposit
func (mr *MockstorageIfcMockRecorder) Deposit(id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockstorageIfc)(nil).Deposit), id, amount)
}

// Withdraw mocks base method
func (m *MockstorageIfc) Withdraw(id int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw
func (mr *MockstorageIfcMockRecorder) Withdraw(id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockstorageIfc)(nil).Withdraw), id, amount)
}

// Transfer mocks base method
func (m *MockstorageIfc) Transfer(senderID, receiverID int, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", senderID, receiverID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer
func (mr *MockstorageIfcMockRecorder) Transfer(senderID, receiverID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockstorageIfc)(nil).Transfer), senderID, receiverID, amount)
}

// GetBalance mocks base method
func (m *MockstorageIfc) GetBalance(id int) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", id)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance
func (mr *MockstorageIfcMockRecorder) GetBalance(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockstorageIfc)(nil).GetBalance), id)
}

// GetTransactionHistory mocks base method
func (m *MockstorageIfc) GetTransactionHistory(id int) (storage.TransactionHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionHistory", id)
	ret0, _ := ret[0].(storage.TransactionHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionHistory indicates an expected call of GetTransactionHistory
func (mr *MockstorageIfcMockRecorder) GetTransactionHistory(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionHistory", reflect.TypeOf((*MockstorageIfc)(nil).GetTransactionHistory), id)
}

// GetTransactionHistoryPage mocks base method
func (m *MockstorageIfc) GetTransactionHistoryPage(id int, sort string, page int) (storage.TransactionHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionHistoryPage", id, sort, page)
	ret0, _ := ret[0].(storage.TransactionHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionHistoryPage indicates an expected call of GetTransactionHistoryPage
func (mr *MockstorageIfcMockRecorder) GetTransactionHistoryPage(id, sort, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionHistoryPage", reflect.TypeOf((*MockstorageIfc)(nil).GetTransactionHistoryPage), id, sort, page)
}
