version: '3.1'

services:

  db:
    build:
      context: ./../
      dockerfile: ./build/docker/db/Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./../db/database/:/var/lib/postgresql/data/
      - ./../db/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5430:5432

  avito-service:
    build:
      context: ./../
      dockerfile: ./build/docker/balance/Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
